// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	dto "backend_capstone/services/productbrand/dto"

	mock "github.com/stretchr/testify/mock"

	models "backend_capstone/models"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddBrandCategory provides a mock function with given fields: brandId, categoryId
func (_m *Service) AddBrandCategory(brandId string, categoryId string) (models.ProductBrandCategory, error) {
	ret := _m.Called(brandId, categoryId)

	var r0 models.ProductBrandCategory
	if rf, ok := ret.Get(0).(func(string, string) models.ProductBrandCategory); ok {
		r0 = rf(brandId, categoryId)
	} else {
		r0 = ret.Get(0).(models.ProductBrandCategory)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(brandId, categoryId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: createbrandDTO
func (_m *Service) Create(createbrandDTO dto.CreateBrandDTO) (models.ProductBrandResponse, error) {
	ret := _m.Called(createbrandDTO)

	var r0 models.ProductBrandResponse
	if rf, ok := ret.Get(0).(func(dto.CreateBrandDTO) models.ProductBrandResponse); ok {
		r0 = rf(createbrandDTO)
	} else {
		r0 = ret.Get(0).(models.ProductBrandResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.CreateBrandDTO) error); ok {
		r1 = rf(createbrandDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: params
func (_m *Service) GetAll(params ...string) (dto.ResponseBodyProductBrand, error) {
	_va := make([]interface{}, len(params))
	for _i := range params {
		_va[_i] = params[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 dto.ResponseBodyProductBrand
	if rf, ok := ret.Get(0).(func(...string) dto.ResponseBodyProductBrand); ok {
		r0 = rf(params...)
	} else {
		r0 = ret.Get(0).(dto.ResponseBodyProductBrand)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...string) error); ok {
		r1 = rf(params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Service) GetById(id string) (models.ProductBrandResponse, error) {
	ret := _m.Called(id)

	var r0 models.ProductBrandResponse
	if rf, ok := ret.Get(0).(func(string) models.ProductBrandResponse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.ProductBrandResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Modify provides a mock function with given fields: id, updatebrandDTO
func (_m *Service) Modify(id string, updatebrandDTO dto.UpdateBrandDTO) (models.ProductBrandResponse, error) {
	ret := _m.Called(id, updatebrandDTO)

	var r0 models.ProductBrandResponse
	if rf, ok := ret.Get(0).(func(string, dto.UpdateBrandDTO) models.ProductBrandResponse); ok {
		r0 = rf(id, updatebrandDTO)
	} else {
		r0 = ret.Get(0).(models.ProductBrandResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, dto.UpdateBrandDTO) error); ok {
		r1 = rf(id, updatebrandDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: id
func (_m *Service) Remove(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveBrandCategory provides a mock function with given fields: brandId, categoryId
func (_m *Service) RemoveBrandCategory(brandId string, categoryId string) error {
	ret := _m.Called(brandId, categoryId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(brandId, categoryId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
