// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	dto "backend_capstone/services/productcategory/dto"

	mock "github.com/stretchr/testify/mock"

	models "backend_capstone/models"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: params
func (_m *Repository) FindAll(params ...string) (int64, *[]dto.ProductCategory, error) {
	_va := make([]interface{}, len(params))
	for _i := range params {
		_va[_i] = params[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 int64
	if rf, ok := ret.Get(0).(func(...string) int64); ok {
		r0 = rf(params...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 *[]dto.ProductCategory
	if rf, ok := ret.Get(1).(func(...string) *[]dto.ProductCategory); ok {
		r1 = rf(params...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*[]dto.ProductCategory)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(...string) error); ok {
		r2 = rf(params...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindById provides a mock function with given fields: id
func (_m *Repository) FindById(id string) (*models.ProductCategoryResponse, error) {
	ret := _m.Called(id)

	var r0 *models.ProductCategoryResponse
	if rf, ok := ret.Get(0).(func(string) *models.ProductCategoryResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProductCategoryResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: data
func (_m *Repository) Insert(data *models.ProductCategory) (*models.ProductCategoryResponse, error) {
	ret := _m.Called(data)

	var r0 *models.ProductCategoryResponse
	if rf, ok := ret.Get(0).(func(*models.ProductCategory) *models.ProductCategoryResponse); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProductCategoryResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.ProductCategory) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, data
func (_m *Repository) Update(id string, data *models.ProductCategory) (*models.ProductCategoryResponse, error) {
	ret := _m.Called(id, data)

	var r0 *models.ProductCategoryResponse
	if rf, ok := ret.Get(0).(func(string, *models.ProductCategory) *models.ProductCategoryResponse); ok {
		r0 = rf(id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProductCategoryResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *models.ProductCategory) error); ok {
		r1 = rf(id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
