// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	dto "backend_capstone/services/transaction/dto"

	mock "github.com/stretchr/testify/mock"
)

// Mailjet is an autogenerated mock type for the Mailjet type
type Mailjet struct {
	mock.Mock
}

// SendBill provides a mock function with given fields: name, email, bill
func (_m *Mailjet) SendBill(name string, email string, bill dto.BillClient) error {
	ret := _m.Called(name, email, bill)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, dto.BillClient) error); ok {
		r0 = rf(name, email, bill)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendInvoice provides a mock function with given fields: name, email, bill
func (_m *Mailjet) SendInvoice(name string, email string, bill dto.BillClient) error {
	ret := _m.Called(name, email, bill)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, dto.BillClient) error); ok {
		r0 = rf(name, email, bill)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
