// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	dto "backend_capstone/utils/midtransdriver/dto"

	mock "github.com/stretchr/testify/mock"

	models "backend_capstone/models"
)

// Midtrans is an autogenerated mock type for the Midtrans type
type Midtrans struct {
	mock.Mock
}

// DoPayment provides a mock function with given fields: method, midtranspaymentDTO
func (_m *Midtrans) DoPayment(method string, midtranspaymentDTO dto.MidtransPaymentDTO) (*models.Payment, error) {
	ret := _m.Called(method, midtranspaymentDTO)

	var r0 *models.Payment
	if rf, ok := ret.Get(0).(func(string, dto.MidtransPaymentDTO) *models.Payment); ok {
		r0 = rf(method, midtranspaymentDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Payment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, dto.MidtransPaymentDTO) error); ok {
		r1 = rf(method, midtranspaymentDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
